config/routes.rb
Rails.application.routes.draw do

  post ':id/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':id/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user
  post ':id/subscribe_user', to: 'relationships#subscribe_user', as: :subscribe_user
  post ':id/unsubscribe_user', to: 'relationships#unsubscribe_user', as: :unsubscribe_user
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'users/show'
  devise_for :users

  resources :users do
    member do
      get :following, :followers
    end
  end
  
  
  resources :categories
  resources :products
  resources :follow
  
  resources :conversations do
  resources :messages
    collection do
      get :inbox
      get :all, action: :index
      get :sent
      get :trash
    end
  end
  
  resources :posts do
    resources :comments
    resource :like, module: :posts
    post :upvote, on: :member
  end
  root 'posts#index'
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
    def index
        @conversations = current_user.mailbox.conversations
    end
    
    def inbox
        @conversations = current_user.mailbox.inbox
        render action: :index
    end

    def sent
        @conversations = current_user.mailbox.sentbox
        render action: :index
    end
    
    def trash
        @conversations = current_user.mailbox.trash
        render action: :index
    end
    
    def show
        @conversation = current_user.mailbox.conversations.find(params[:id])
        @conversation.mark_as_read(current_user)
        @message = Mailboxer::Message.new
    end
    
    def new
        @recipients = User.all - [current_user]
    end
    
    def create
        recipient = User.find(params[:user_id])
        receipt = current_user.send_message(recipient, params[:body], params[:subject])
        redirect_to conversation_path(receipt.conversation)
    end
    
end

app/views/conversations/index.html.erb
<h1>All conversations</h1>

<hr />
Inbox (<%= current_user.mailbox.inbox.count %>) |
All Conversations (<%= current_user.mailbox.conversations.count %>) |
Sent (<%= current_user.mailbox.sentbox.count %>) |
Trash (<%= current_user.mailbox.trash.count %>) |
<hr />

Total: <%= @conversations.count %>

<% @conversations.each do |conversation| %>
<div>
    <% if conversation.is_unread?(current_user) %>
        <strong><%= link_to conversation.subject, conversation_path(conversation) %></strong>
    <% else %>
        <%= link_to conversation.subject, conversation_path(conversation) %>
    <% end %>

</div>
<% end %>
<%= link_to "New Conversation", new_conversation_path %>

app/views/conversations/new.html.erb
<h1>New Converastion</h1>

<%= form_tag conversations_path, method: :post do %>
    <div>
        <%= select_tag :user_id, options_from_collection_for_select(@recipients, :id, :username) %>
    </div>
    
    <div>
        <%= text_field_tag :subject, nil, placeholder: "Subject" %>
    </div>
    
    <div>
        <%= text_area_tag :body, nil,  placeholder: "Leave a comment" %>
    </div>
    
    <%= submit_tag %>
<% end %>

app/views/conversations/show.html.erb
<h1><%= @conversation.subject %></h1>

<% @conversation.receipts_for(current_user).each do |receipt| %>
<div>
    <div> <%= receipt.message.sender.username %> wrote:</div>
    <p><%= receipt.message.body %></p>
</div>

<% end %>

<%= form_tag conversation_messages_path(@conversation), method: :post do %>
    <div>
        <%= text_area_tag :body %>
    </div>
    
    <%= submit_tag %>
<% end %>