config/routes.rb
Rails.application.routes.draw do

  post ':id/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':id/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user
  post ':id/subscribe_user', to: 'relationships#subscribe_user', as: :subscribe_user
  post ':id/unsubscribe_user', to: 'relationships#unsubscribe_user', as: :unsubscribe_user
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'users/show'
  devise_for :users

  resources :users do
    member do
      get :following, :followers
    end
  end
  
  
  resources :categories
  resources :products
  resources :follow
  
  resources :conversations do
  resources :messages
    collection do
      get :inbox
      get :all, action: :index
      get :sent
      get :trash
    end
  end
  
  resources :posts do
    resources :comments
    resource :like, module: :posts
    post :upvote, on: :member
  end
  root 'posts#index'
end

app/models/user.rb
class User < ApplicationRecord

  has_many :posts
  has_many :comments
  has_many :votes
  has_many :likes
  #following relationship
  has_many :follower_relationships, foreign_key: :following_id, class_name: 'Follow'
  has_many :followers, through: :follower_relationships, source: :follower

  has_many :following_relationships, foreign_key: :follower_id, class_name: 'Follow'
  has_many :following, through: :following_relationships, source: :following

  has_many :subscriber_relationships, foreign_key: :subscription_id, class_name: 'Subscribe'
  has_many :subscribers, through: :subscriber_relationships, source: :subscriber

  has_many :subscription_relationships, foreign_key: :subscriber_id, class_name: 'Subscribe'
  has_many :subscription, through: :subscription_relationships, source: :subscription



  mount_uploader :avatar, AvatarUploader

  acts_as_messageable
  after_create :create_default_likes

  def mailboxer_email(object)
    email
  end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    # User Avatar Validation
  validates_integrity_of  :avatar
  validates_processing_of :avatar
  
  
  #Voting methods
  def upvote(post)
    votes.create(upvote: 1, post: post)
  end
  
  def upvoted?(post)
    votes.exists?(upvote: 1, post: post)
  end
  
  def remove_vote(post)
    votes.find_by(post: post).destroy
  end
  
  def likes?(post)
    post.likes.where(user_id: id).any?
  end
  
  
  # Follow methods
  def follow(user_id)  
    following_relationships.create(following_id: user_id)
  end

  def unfollow(user_id)
    following_relationships.find_by(following_id: user_id).destroy
  end


    def subscribe(category_id)  
        subscription_relationships.create(subscription_id: category_id)
    end

    def unsubscribe(category_id)
        subscription_relationships.find_by(subscription_id: category_id).destroy
    end

  
  
  private
    def avatar_size_validation
      errors[:avatar] << "should be less than 500KB" if avatar.size > 0.5.megabytes
    end
    
    def create_default_likes
        # Create your likes here
        [2,3,4].each do |id|
            likes.create post_id: id
        end
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @user_posts = @user.posts.order("created_at DESC")
    @user_comments = @user.comments.order("created_at DESC")
  
  end
  
  def following
    @user = User.find(params[:id])
  end

  def followers
    @user = User.find(params[:id])
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def current_user_is_following(current_user_id, followed_user_id)
    relationship = Follow.find_by(follower_id: current_user_id, following_id: followed_user_id)
    return true if relationship
  end
  
  def current_category_is_subscribed(current_user_id, subscribed_category_id)
    relationship = Subscribe.find_by(subscriber_id: current_user_id, subscription_id: subscribed_category_id)
    return true if relationship
  end
end

app/views/users/_left_user.erb
<div style="background: #F7F7F7; margin-top: 10px;">
    <a style="padding-left: 15px;"><a class="user-title"><%= @user.username %></a></a>
</div>
<div class="user-block">
    <div class="profile">
        <%= image_tag @user.avatar.url(:thumb)%>
    </div>
    <div class="user-nav">
        <a><%= link_to "Private Message", conversation_path(@user.id)  %></a></br>
        <a><%= link_to "Add as Friend", conversation_path(@user.id)  %></a></br>
        <a><%= link_to "Latest Posts", conversation_path(@user.id)  %></a></br>
        <a><%= link_to "Find latest posts", conversation_path(@user.id)  %></a></br>
    </div>
</div>
<div>
    <span>
    <% if @user == current_user %>
      <%= link_to 'Edit Profile', edit_user_registration_path(@user.id), class: 'btn edit-button' %>
    <% else %>
      <% if current_user_is_following(current_user.id, @user.id) %>
        <%= link_to 'Following', unfollow_user_path, remote: true, class: 'btn unfollow-button', id: 'unfollow-button', method: :post %>
      <% else %>
        <%= link_to 'Follow', follow_user_path, remote: true, class: 'btn follow-button', id: 'follow-button', method: :post %>
      <% end %>
    <% end %>
    </span>
</div>
<div class="stats">
    <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
    <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/users/followers.html.erb
<% @user.followers.each do |followers| %>
    
<div class="col-sm-4">
    <div class="card">
        <div class="card-block">
            <div class="user-block">
                <div class="profile">
                    <%= image_tag followers.avatar.url(:thumb)%>
                </div>
                <div class="user-nav">
                  <h3><%= followers.username%></h3>
                  <p>Strap that boot!</p>
                  <p>Posts: <%= followers.posts.count%></p>
                </div>
            </div>
            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
            <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
        <div>
            <span>

              <% if current_user_is_following(current_user.id, @user.id) %>
                <%= link_to 'Following', unfollow_user_path, remote: true, class: 'btn unfollow-button', id: 'unfollow-button', method: :post %>
              <% else %>
                <%= link_to 'Follow', follow_user_path, remote: true, class: 'btn follow-button', id: 'follow-button', method: :post %>
              <% end %>

            </span>
        </div>
    </div>
</div>
<% end %>

app/views/users/following.html.erb
<% @user.following.each do |following| %>
    
  <div class="col-sm-4">
    <div class="card">
      <div class="card-block">
        <div class="user-block">
            <div class="profile">
                    <%= image_tag following.avatar.url(:thumb)%>
            </div>
            <div class="user-nav">
                  <h3><%= following.username%></h3>
                  <p>Strap that boot!</p>
                  <p>Posts: <%= following.posts.count%></p>
            </div>
        </div>
        <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
        <a href="#" class="btn btn-primary">Go somewhere</a>
      </div>
      
        <div>
            <span>
              <% if current_user_is_following(current_user.id, @user.id) %>
                <%= link_to 'Following', unfollow_user_path, remote: true, class: 'btn unfollow-button', id: 'unfollow-button', method: :post %>
              <% else %>
                <%= link_to 'Follow', follow_user_path, remote: true, class: 'btn follow-button', id: 'follow-button', method: :post %>
              <% end %>
            </span>
        </div>
    </div>
  </div>




<% end %>

app/views/users/show.html.erb
<div class="row">
    <div class="col-11 col-offset-250">
        <% @user_posts.each do |post| %>
            <h2><%=link_to post.title, post_path(post) %></h2>
                <p class="post-posted-by">Posted <%= time_ago_in_words(post.created_at) %> ago by <%= User.find(post.user_id).email %> in <%= link_to Category.find(post.category_id).name, category_path(post.category_id) %> </p>
                    <div class="post-nav">
                        <a href="#">Share</a>
                        <a href="#">Save</a>
                        <a href="#">Report</a>
                    </div>
        <% end %>
        <% @user_comments.each do |comment| %>
            <h2><%= comment.content %></h2>
        <% end %>

    </div>
    <div class="col-fixed-250">
        <%= render 'users/left_user' %>
    </div>
</div>