config/routes.rb
Rails.application.routes.draw do

  post ':id/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':id/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user
  post ':id/subscribe_user', to: 'relationships#subscribe_user', as: :subscribe_user
  post ':id/unsubscribe_user', to: 'relationships#unsubscribe_user', as: :unsubscribe_user
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'users/show'
  devise_for :users

  resources :users do
    member do
      get :following, :followers
    end
  end
  
  
  resources :categories
  resources :products
  resources :follow
  
  resources :conversations do
  resources :messages
    collection do
      get :inbox
      get :all, action: :index
      get :sent
      get :trash
    end
  end
  
  resources :posts do
    resources :comments
    resource :like, module: :posts
    post :upvote, on: :member
  end
  root 'posts#index'
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    belongs_to :category
    has_many :comments
    has_many :votes
    has_many :likes
    
    require 'rest-client'
    require 'json'
   

    
    searchkick
    
    scope :published, ->{ where.not(created_at: nil) }
    scope :unpublished, ->{ where(created_at: nil) }
    



    
    def upvotes
        votes.sum(:upvote)
    end
    
    def search_data
        {
          title: title,
          description: description
        }
    end
end

app/controllers/posts/likes_controller.rb
class Posts::LikesController < ApplicationController
    before_action :authenticate_user!
    before_action :set_post
    
    def create
        @post.likes.where(user_id: current_user.id).first_or_create
        
        respond_to do |format|
            format.html { redirect_to @post }
            format.js
        end
    end
    
    def destroy
        @post.likes.where(user_id: current_user.id).destroy_all
        
        respond_to do |format|
            format.html { redirect_to @post }
            format.js
        end
    end
    
    
    private
    
        def set_post
            @post = Post.find(params[:post_id])
        end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :find_post, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, except: [:index, :show]
    helper_method :resource_name, :resource, :devise_mapping, :resource_class
    

    
    def index
        unless user_signed_in?
            query = params[:q].presence || "*"
            @posts = Post.all.order("created_at DESC")
            @posts = Post.search(query)
            
            url = "https://api.coinmarketcap.com/v1/ticker/"
            response = RestClient.get(url)
            data=response.body
            @result = JSON.parse(data)

            
            
        else
            query = params[:q].presence || "*"
            @posts = Post.all.order("created_at DESC")
            @posts = Post.search(query)
            @likes = current_user.likes

            url = "https://api.coinmarketcap.com/v1/ticker/"
            response = RestClient.get(url)
            data=response.body
            @result = JSON.parse(data)
        end

    end
    
    def show
    end
    
    
    def new 
        @post = Post.new 
        @categories = Category.all.map{|c| [ c.name, c.id ] }
    end

    
    def create
        @post = current_user.posts.build(post_params)
        @post.category_id = params[:category_id] 

        respond_to do |format| 
            if @post.save
                format.html { redirect_to @post, notice: ('post was successfully created.') } 
                format.json { render :show, status: :created, location: @post } 
            else
                format.html { render :new } 
                format.json { render json: @post.errors, status: :unprocessable_entity } 
            end
        end
    end
    
    def edit
        @categories = Category.all.map{|c| [ c.name, c.id ] }
    end
    
    def update
        if @post.update(post_params)
            redirect_to post_path
        else
            render 'edit'
        end
        @post.category_id = params[:category_id]
    end
    
    def destroy
        @post.destroy
        redirect_to root_path
    end
    
    
    def resource_name
    :user
    end
    
    def resource
    @resource ||= User.new
    end
    
    def resource_class
    User
    end
    
    def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
    end
    
    
    private
    
        def post_params
            params.require(:post).permit(:title, :description)
        end
        
        def find_post
            @post = Post.find(params[:id])
        end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
    <%= f.input :title, label: "Post Title" %>
    <%= f.input :description, :input_html => {:rows => 10} %>
    <%= f.button :submit %>
    <%= select_tag(:category_id, options_from_collection_for_select(Category.all, :id, :name), include_blank: "Select Category") %>
<% end %>

app/views/posts/_left.erb
<% if !user_signed_in? %>
    <%= render '/posts/left_guest' %>
<% else %>
    <%= render '/posts/left_user' %>
<% end %>

app/views/posts/_left_guest.erb
<%= form_for(:user, :url => session_path(:user)) do |f| %>
  </br>
  <%= f.text_field :email %></br>
  <%= f.password_field :password %> </br>
  <%= f.check_box :remember_me %>
  <%= f.label :remember_me %></br>
  <%= f.submit 'Sign in' %></br>
  <%= link_to('Sign Up', new_user_registration_path)  %></br>
  <%= link_to "Forgot your password?", new_password_path(:user) %>
<% end %>

app/views/posts/_left_user.erb
<div style="background: #F7F7F7; margin-top: 10px;">
    <a class="user-title"><%= current_user.username %></a>
</div>
<div class="user-block">
    <div class="profile">
        <%= image_tag current_user.avatar.url(:thumb) %>
    
    </div>
    <div class="user-nav">
        <a><%= link_to "Messages", "/conversations"  %></a> (<%= current_user.mailbox.inbox(:unread => true).count %>)</br>
        <a><%= link_to "Saved Posts", user_path(current_user.id)  %></a></br>
        <a><%= link_to 'Preferences', edit_user_registration_path  %></a></br>
        <a><%= link_to 'Sign Out', destroy_user_session_path, method: :delete  %></a></br>
    </div>
</div>
<div class="stats">
    <a href="<%= following_user_path(current_user) %>">
    <strong id="following" class="stat">
      <%= current_user.following.count %>
    </strong>
    following
    </a>
    <a href="<%= followers_user_path(current_user) %>">
    <strong id="followers" class="stat">
      <%= current_user.followers.count %>
    </strong>
    followers
    </a>
</div>


<div class="stats">
    <strong id="following" class="stat">
      <%= current_user.subscription.count %>
    </strong>
    Subscriptions
  </a>
</div>


<div>
    <a><%= link_to "New Post", new_post_path %></a></br>
    <a><%= link_to "New Category", new_category_path %></a></br>
    <a><%= link_to "My Posts", user_path(current_user.id)  %></a></br>
    <a><%= link_to "My Gigs", user_path(current_user.id)  %></a></br>
    <a><%= link_to "My Comments", user_path(current_user.id)  %></a></br>
</div>
<div style="background: #F7F7F7;">
    <a style="padding-left: 15px;">Favorite Posts</a>
</div>

<div class="liked-posts">
<% @likes.reverse.each do |like| %>
    <%= link_to image_tag('del.png'), post_like_path(like.post), method: :delete, :class=>"unlike" %>
    <%= link_to like.post.title.truncate(28), post_path(like.post_id), :maxlength => 10  %></br>
<% end %>

</div>

<div style="background: #F7F7F7;">
    <a style="padding-left: 15px;">Prices</a>
</div>


<div class="row">
    <% current_user.subscription.each do |subscription| %>
        <%= subscription.name%>:
        <%= @result[subscription.ticker_id]["price_usd"] %></br>
    <% end %>
</div>

app/views/posts/_likes.html.erb
<% if user_signed_in? && current_user.likes?(post) %>
    <%= link_to "Unlike", post_like_path(post), method: :delete, remote: true %>
<% else %>
    <%= link_to "Like", post_like_path(post), method: :post, remote: true %>
<% end %>

<%= post.likes.count %>

app/views/posts/edit.html.erb
<h1>Edit post</h1>
<%= render 'form' %>

app/views/posts/index.html.erb
<div class="row">
    <div class="col-11 col-offset-250">
        <span class="notice"><%= notice %></span>
        <span class="alert"><%= alert %></span>
        <% @posts.each do |post| %>
        <h2><%=link_to post.title, post_path(post) %></h2>
        <p class="post-posted-by">Posted <%= time_ago_in_words(post.created_at) %> ago by <%= link_to User.find(post.user_id).username, user_path(post.user_id) %> in <%= link_to Category.find(post.category_id).name, category_path(post.category_id) %> </p>
            <div class="post-nav">
                <a href="http://www.facebook.com/">Share</a>
                <a href="#">Save</a>
                <a href="#">Report</a>
                <span id="post_<%= post.id %>_likes"><%= render partial: "likes", locals: {post: post} %></span>
            </div>
        <% end %>
        </br>
        <%= link_to "New post", new_post_path %>
    </div>
    <div class="col-fixed-250">
        <%= render "/posts/left" %>
    </div>

</div>

app/views/posts/new.html.erb
<div class="col-md-8 col-md-offset-2">
    <h1>New post</h1>
    
    <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div class="col-md-8 col-md-offset-2">
    <div class="post-show">
        <h2><%= @post.title %></h2>
        <p class="post-posted-by">Posted by <%= @post.user.email %> <%= time_ago_in_words(@post.created_at) %> ago in <%= link_to Category.find(@post.category_id).name, category_path(@post.category_id) %> </p>
        <p class="post-desc"><%= @post.description.html_safe %></p>
        <div class="links btn-group">
            <% if user_signed_in? %>
                <% if @post.user_id == current_user.id %>
                    <%= link_to "Edit", edit_post_path(@post), class: "btn btn-default" %>
                    <%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default" %>
                <% end %>
            <% end %>
            <div id="post_<%= @post.id %>_likes">
                <%= render partial: "likes", locals: {post: @post} %>
            </div>
        </div>
        
        <h3>Comments:</h3>
        <%= render @post.comments %>
        
        <h3 class="reply-to-msg">Reply to post:</h3>
        <%= render 'comments/form' %>
    </div>
</div>