config/routes.rb
Rails.application.routes.draw do

  post ':id/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':id/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user
  post ':id/subscribe_user', to: 'relationships#subscribe_user', as: :subscribe_user
  post ':id/unsubscribe_user', to: 'relationships#unsubscribe_user', as: :unsubscribe_user
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'users/show'
  devise_for :users

  resources :users do
    member do
      get :following, :followers
    end
  end
  
  
  resources :categories
  resources :products
  resources :follow
  
  resources :conversations do
  resources :messages
    collection do
      get :inbox
      get :all, action: :index
      get :sent
      get :trash
    end
  end
  
  resources :posts do
    resources :comments
    resource :like, module: :posts
    post :upvote, on: :member
  end
  root 'posts#index'
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :posts
    

    
    
    def index
        @categories = Category.all
    end
    
    def show
        @category = Category.find(params[:id])
    end
    
    def new
        @category = Category.new(category_params)
    end
    
    def create
        @category = Category.create(category_params)
        if @category.save
            flash[:success] = "Category successfully saved!"
            redirect_to :category
        else
            flash[:error] ="Category was not saved!"
            render :new
        end
    end
    
    def edit
        @category = Category.find(params[:id])
    end
    
    def update
        @category = Category.update(category_params)
        if @category.save
            flash[:success] = "Category successfully updated!"
            redirect_to @category
        else
            flash[:error] ="Category was not updated!"
            render :edit
        end
    end
    
    def destroy
        Category.find(params[:id]).destroy
    end




    
    private
    
        def category_params
            params.require(:cateogry).permit(:name, :desc)
        end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :desc)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :desc %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Desc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.desc %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @category.desc %>
</p>
<h3> Posts under this category </h3>
<% Post.where(category_id: @category.id).each do |post| %>
<li> <%= link_to post.title, post_path(post) %> </li>
<% end %>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>


    <span>
    <% if @user == current_user %>
      <%= link_to 'Edit Profile', edit_user_registration_path(@user.id), class: 'btn edit-button' %>
    <% else %>
      <% if current_category_is_subscribed(current_user.id, @category.id) %>
        <%= link_to 'Unsubscribe', unsubscribe_user_path, remote: true, class: 'btn unfollow-button', id: 'unfollow-button', method: :post %>
      <% else %>
        <%= link_to 'Subscribe', subscribe_user_path, remote: true, class: 'btn follow-button', id: 'follow-button', method: :post %>
      <% end %>
    <% end %>
    </span>
    